export enum INPUT_COMMAND {
    // MOVE_DIRECTION,
    HORIZONTAL_UP,
    HORIZONTAL_DOWN,
    VERTICAL_LEFT,
    VERTICAL_RIGHT,
    LEFT_MOUSE,
    RIGHT_MOUSE,
    MIDDLE_MOUSE,
    INTERACT,
    SWITCH_WEAPON,
    TEST,
}
